version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web: &web
    container_name: ${PROJECT_NAME}_web
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    env_file: .env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: always

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:6-alpine
    restart: always

#  celery:
#    container_name: ${PROJECT_NAME}_celery
#    <<: *web
#    ports: [ ]
#    command: celery -A config worker --beat --scheduler django --loglevel=info
#    restart: always

volumes:
  postgres_data:
  static_volume:
